version: '1'
services:

  frontend:
    container_name: weather-frontend
    restart: always
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile

  backend:
    container_name: weather-backend
    restart: always
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - NODE_ENV=production
    #   - GEOCODE_API_KEY=PUT-API-KEY-HERE
    #   - WEATHER_API_KEY=PUT-API-KEY-HERE

    # env_file for API keys
    env_file:
      - .env

  nginx-proxy:
    container_name: weather-proxy
    restart: always
    build: 
      context: .
      dockerfile: ./docker/proxy/Dockerfile
    ports:
      - "8080:8080"